files = [
    { type = "software-management", path = "/var/log/tedge/agent/software-*" },
    { type = "shell", path = "/var/log/tedge/agent/c8y_Command-*" },
    { type = "dpkg", path = "/var/log/dpkg.log" },
    { type = "apt-terminal-log", path = "/var/log/apt/term.log" },
    { type = "modbus", path = "/var/log/te-modbus-plugin/modbus.log" }
]